"""empty message

Revision ID: 6060e9c7923a
Revises:
Create Date: 2017-11-19 21:52:40.763142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6060e9c7923a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trello_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_token', sa.String(length=255), nullable=True),
    sa.Column('auth_api_key', sa.String(length=255), nullable=True),
    sa.Column('auth_api_secret', sa.String(length=255), nullable=True),
    sa.Column('auth_token_secret', sa.String(length=255), nullable=True),
    sa.Column('default_board', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token')
    )
    op.create_table('alexa_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('trello_user_id', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trello_user_id'], ['trello_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alexa_users')
    op.drop_table('trello_users')
    # ### end Alembic commands ###
